#define GAME_TITLE "Beat 'Em Up!"

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define FONT_SIZE 32

#define ANCHOR_TYPE_CENTER 0
#define ANCHOR_TYPE_TOP_LEFT 1
#define ANCHOR_TYPE_BOTTOM_LEFT 2
#define ANCHOR_TYPE_TOP_RIGHT 3

#define IMAGE_SOURCE_WIDTH 0
#define IMAGE_SOURCE_HEIGHT 0

#define KEY_QUIT SDLK_ESCAPE
#define KEY_MOVE_UP SDLK_w
#define KEY_MOVE_DOWN SDLK_s
#define KEY_MOVE_LEFT SDLK_a
#define KEY_MOVE_RIGHT SDLK_d
#define KEY_LIGHT_ATTACK SDLK_e
#define KEY_HEAVY_ATTACK SDLK_r
#define KEY_NEW_GAME SDLK_n
