#pragma once

#define GAME_TITLE "Beat 'Em Up!"

#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480

#define FONT_SIZE 32

#define ANCHOR_TYPE_CENTER 0
#define ANCHOR_TYPE_TOP_LEFT 1
#define ANCHOR_TYPE_BOTTOM_LEFT 2
#define ANCHOR_TYPE_TOP_RIGHT 3
#define ANCHOR_TYPE_TOP_CENTER 4

#define IMAGE_SOURCE_WIDTH 0
#define IMAGE_SOURCE_HEIGHT 0

#define KEY_QUIT SDLK_ESCAPE
#define KEY_MOVE_UP SDLK_w
#define KEY_MOVE_DOWN SDLK_s
#define KEY_MOVE_LEFT SDLK_a
#define KEY_MOVE_RIGHT SDLK_d
#define KEY_LIGHT_ATTACK SDLK_e
#define KEY_HEAVY_ATTACK SDLK_r
#define KEY_NEW_GAME SDLK_n

#define PLAYER_SPEED 200

#define LIGHT_ATTACK_TIME 400
#define HEAVY_ATTACK_TIME 800

#define UP_DIRECTION -1
#define DOWN_DIRECTION 1
#define LEFT_DIRECTION -1
#define RIGHT_DIRECTION 1

#define FLOOR_HEIGHT (0.6*WINDOW_HEIGHT)
#define FLOOR_TILE_COUNT 3

#define INFO_BOX_HEIGHT FONT_SIZE+2*INFO_BOX_PADDING
#define INFO_BOX_PADDING 10

#define IMPLEMENTED_TEXT "Impl: 1, 2, 3, 4, A"
